Repository intel/graph-compiler, pull requests merged in 2024-09, with the labels that each got.

#311 [Transform][Fusion] loose `isTiledOpInLoop` check to cover no `insert_slice` case
  lib/gc/Transforms/IterativeTilingAndFusion.cpp
  test/mlir/test/gc/Transforms/iterative-tiling-and-fusion.mlir
Labels: ready to review

#287 [Transform] Only use gc runtime allocator for stack-like alloca ops
  lib/gc/Transforms/MemRefToCPURuntime.cpp
  lib/gc/Transforms/Pipeline.cpp
  test/mlir/test/gc/Dialect/CPURuntime/memref-to-cpuruntime.mlir
Labels: ready to review, CPU

#309 Refactor the deep tile matmul config and skip the single-iteration loop generation
  include/gc/Analysis/MatmulConfigAnalysis.h
  lib/gc/Analysis/MatmulConfigAnalysis.cpp
  lib/gc/Transforms/DeepTileContractionOp.cpp
  test/mlir/test/gc/Transforms/deepTileContractionNamedOp.mlir
Labels: ready to review

#310 [Transform] fix legalization on absi
  lib/gc/Transforms/Pipeline.cpp
Labels: ready to review

#296 [Transform] Introduce `microkernel` dialect optimization passes
  include/gc/Transforms/Microkernel/MicrokernelPasses.td
  lib/gc/Dialect/Microkernel/MicrokernelOps.cpp
  lib/gc/Transforms/CMakeLists.txt
  lib/gc/Transforms/Microkernel/CMakeLists.txt
  lib/gc/Transforms/Microkernel/ConvertLinalgToMicrokernel.cpp
  lib/gc/Transforms/Microkernel/EarlyDispatchMicrokernel.cpp
  lib/gc/Transforms/Microkernel/MergeBranchMicrokernelContext.cpp
  lib/gc/Transforms/Microkernel/MicrokernelInvariantCodeMotion.cpp
  lib/gc/Transforms/Pipeline.cpp
  lib/gc/Transforms/Utils/ValueUtils.cpp
  test/mlir/test/gc/Dialect/Microkernel/early-dispatch-microkernel.mlir
  test/mlir/test/gc/Dialect/Microkernel/merge-branch-microkernel-context.mlir
  test/mlir/test/gc/Dialect/Microkernel/microkernel-invariant-code-motion.mlir
  test/mlir/test/gc/cpu-runner/brgemm-multilevel-for.mlir
  test/mlir/test/gc/cpu-runner/brgemm-parallel.mlir
  test/mlir/test/gc/cpu-runner/brgemm-simple-for.mlir
Labels: ready to review

#316 [Transform][Fusion] fix `whileProducerOutOfLoopBlock` logic
  lib/gc/Transforms/IterativeTilingAndFusion.cpp
  lib/gc/Transforms/TilingUsingInterfaceX.cpp
  lib/gc/Transforms/TilingUsingInterfaceX.h
  test/mlir/test/gc/Transforms/iterative-tiling-and-fusion.mlir
Labels: ready to review

#286 [Transform][Vector] Support vector methods in the new llvm version
  lib/gc/Transforms/LowerToTileVector.cpp
  test/mlir/test/gc/Transforms/vectorization.mlir
Labels: ready to review

#312 [BenchGC] attach DLTI for mlir module
  python/CMakeLists.txt
  python/CPUInfo.cpp
  python/gc_mlir/tools/__init__.py
  python/gc_mlir/tools/cpuinfo.py
  test/benchgc/README.md
  test/benchgc/setup.py
  test/benchgc/src/benchgc/__main__.py
  test/benchgc/src/benchgc/mlir/util.py
Labels: ready to review

#328 [Build] fix issue when GC_DEV_LINK_LLVM_DYLIB is ON
  lib/gc/Transforms/CMakeLists.txt
  lib/gc/Transforms/Microkernel/CMakeLists.txt
  test/benchgc/src/benchgc/mlir/util.py
Labels: ready to review

#307 [Linalgx] Deprecate all linalgx matmul ops
  include/gc/Analysis/MatmulConfigAnalysis.h
  include/gc/Dialect/Linalgx/LinalgxStructuredOps.td
  include/gc/Dialect/Linalgx/Utils.h
  lib/gc/Dialect/Linalgx/LinalgxOps.cpp
  lib/gc/Transforms/DeepTileContractionOp.cpp
  lib/gc/Transforms/IterativeTilingAndFusion.cpp
  lib/gc/Transforms/LowerToTileVector.cpp
  test/mlir/test/gc/Dialect/Linlagx/generalize-named-ops.mlir
  test/mlir/test/gc/Dialect/Linlagx/linalgx-named-ops.mlir
  test/mlir/test/gc/Transforms/deepTileContractionNamedOp.mlir
  test/mlir/test/gc/Transforms/iterative-tiling-and-fusion.mlir
Labels: ready to review, CPU

#220 [GPU] Add MLP test and linalg.fill lowering in 'linalg-to-xegpu'
  .github/workflows/build-llvm.yml
  cmake/imex-version.txt
  cmake/imex.cmake
  lib/gc/Transforms/GPU/LinalgToXeGPU.cpp
  scripts/compile.sh
  test/mlir/test/gc/gpu-runner/XeGPU/f16_mlp_32x4096x4096x4096.mlir
Labels: test, ready to review

#329 [GPU] Register initial GPU pipeline that uses IMEX
  include/gc/Transforms/Passes.h
  lib/gc/Transforms/GPU/CMakeLists.txt
  lib/gc/Transforms/GPU/LinalgToXeGPU.cpp
  lib/gc/Transforms/GPU/Pipeline.cpp
  src/gc-opt/gc-opt.cpp
  test/mlir/test/gc/gpu-runner/XeGPU/f16_matmul_32x32.mlir
  test/mlir/test/gc/gpu-runner/XeGPU/f16_matmul_64x64.mlir
  test/mlir/test/gc/gpu-runner/XeGPU/f16_mlp_32x4096x4096x4096.mlir
  test/mlir/test/gc/gpu-runner/mlp.mlir
Labels: ready to review, GPU

#294 [CPU][Runtime] Set some CPURuntime funcs visibility to default
  include/gc/ExecutionEngine/CPURuntime/Microkernel/BrgemmInterface.h
  include/gc/Utils.h
  lib/gc/ExecutionEngine/CPURuntime/MemoryPool.cpp
  lib/gc/ExecutionEngine/OpenCLRuntime/CMakeLists.txt
  lib/gc/ExecutionEngine/OpenCLRuntime/OpenCLRuntimeWrappers.cpp
  src/dnnl/dnnl_graph_compiler.cpp
Labels: ready to review

#348 [Transform][Fusion] align file name with upstream
  lib/gc/Transforms/CMakeLists.txt
  lib/gc/Transforms/IterativeTilingAndFusion.cpp
  lib/gc/Transforms/Pipeline.cpp
  lib/gc/Transforms/TileUsingInterfaceX.cpp
  lib/gc/Transforms/TileUsingInterfaceX.h
  lib/gc/Transforms/TilingUtil.hpp
Labels: ready to review

#283 [Transform] Hoist thread-local allocator within the nested parallel loops
  lib/gc/Transforms/MergeAllocTickBased.cpp
  test/mlir/test/gc/Transforms/buffer-merge-lifetime.mlir
  test/mlir/test/gc/Transforms/buffer-merge.mlir
Labels: ready to review, CPU

#354 Add an option for insert gpu allocs to treat allocations as gpu-native
  cmake/imex-version.txt
  include/gc/Transforms/Passes.h
  lib/gc/Transforms/GPU/Pipeline.cpp
  test/mlir/test/gc/gpu-runner/XeGPU/f16_matmul_64x64.mlir
  test/mlir/test/gc/gpu-runner/XeGPU/f16_mlp_32x4096x4096x4096.mlir
Labels: ready to review

#333 Convert a subset of GPU dialect ops to the OpenCL GPU runtime calls
  include/gc/ExecutionEngine/GPURuntime/GpuOclRuntime.h
  include/gc/Transforms/Passes.td
  lib/gc/Transforms/GPU/AddContextArg.cpp
  lib/gc/Transforms/GPU/CMakeLists.txt
  lib/gc/Transforms/GPU/GpuToGpuOcl.cpp
  test/mlir/test/gc/Transforms/GPU/gpu-to-gpuocl.mlir
Labels: GPU

#357 Update llvm commit
  cmake/imex-version.txt
  cmake/llvm-version-imex.txt
  cmake/llvm-version.txt
  test/mlir/test/gc/gpu-runner/mlp.mlir
Labels: ready to review

#363 Update llvm commit
  cmake/llvm-version.txt
Labels: ready to review

#347 [LinalgToXeGPU] Lower `linalg.matmul_transpose_b` into `xegpu.dpas`
  lib/gc/Transforms/GPU/LinalgToXeGPU.cpp
  test/mlir/test/gc/Transforms/GPU/linalg-to-xegpu-dpas-transpose-sep-alloc.mlir
  test/mlir/test/gc/Transforms/GPU/linalg-to-xegpu-dpas-transpose-sep.mlir
  test/mlir/test/gc/Transforms/GPU/linalg-to-xegpu-dpas-transpose.mlir
  test/mlir/test/gc/gpu-runner/XeGPU/f16_matmul_128x64_transpose.mlir
  test/mlir/test/gc/gpu-runner/XeGPU/f16_matmul_128x64_transpose_sep.mlir
  test/mlir/test/gc/gpu-runner/XeGPU/f16_mlp_32x4096x4096x4096_transpose.mlir
Labels: GPU
