Repository intel/graph-compiler, pull requests merged in 2024-08, with the labels that each got.

#213 remove bindings and skip tests when GC_ENABLE_DNNL=OFF
  python/CMakeLists.txt
  python/MainModule.cpp
  python/gc_mlir/_mlir_libs/_site_initialize_0.py
  test/mlir/test/gc/Dialect/OneDNNGraph/lit.local.cfg
  test/mlir/test/gc/python/dialects/lit.local.cfg
  test/mlir/test/gc/python/lit.local.cfg
  test/mlir/test/lit.site.cfg.py.in
Labels: ready to review

#87 [Transform][Fusion] Introduce an iterative tiling and fusion pass in forward and backward fashion
  include/gc/Transforms/Passes.td
  lib/gc/Transforms/CMakeLists.txt
  lib/gc/Transforms/IterativeTilingAndFusion.cpp
  lib/gc/Transforms/Pipeline.cpp
  lib/gc/Transforms/TilingUsingInterfaceX.cpp
  lib/gc/Transforms/TilingUsingInterfaceX.h
  test/gc/Transform/iterative-tiling-and-fusion.mlir
Labels: ready to review

#210 Centralize target description query through DLTI and add verifier pass
  include/gc/Analysis/TargetDescriptionAnalysis.h
  include/gc/Transforms/Passes.td
  lib/gc/Analysis/CMakeLists.txt
  lib/gc/Analysis/TargetDescriptionAnalysis.cpp
  lib/gc/CAPI/CMakeLists.txt
  lib/gc/CMakeLists.txt
  lib/gc/ExecutionEngine/Driver/CMakeLists.txt
  lib/gc/Transforms/CMakeLists.txt
  lib/gc/Transforms/IterativeTilingAndFusion.cpp
  lib/gc/Transforms/Pipeline.cpp
  lib/gc/Transforms/VerifyTargetDescription.cpp
  src/gc-opt/CMakeLists.txt
  test/mlir/unittests/Analysis/CMakeLists.txt
  test/mlir/unittests/Analysis/TargetDescriptionAnalysisTest.cpp
  test/mlir/unittests/CMakeLists.txt
Labels: ready to review

#216 only emit target description warning in verify phase and correct the target op
  include/gc/Analysis/TargetDescriptionAnalysis.h
  lib/gc/Analysis/TargetDescriptionAnalysis.cpp
  lib/gc/Transforms/Pipeline.cpp
  lib/gc/Transforms/VerifyTargetDescription.cpp
Labels: ready to review

#223 Enable affine op lowering
  lib/gc/Transforms/Pipeline.cpp
Labels: ready to review

#201 Aling 'linalg-to-xegpu' pass with patched XeGPU dialect
  cmake/imex.cmake
  include/gc/Transforms/Passes.td
  lib/gc/ExecutionEngine/Driver/CMakeLists.txt
  lib/gc/ExecutionEngine/OpenCLRuntime/OpenCLRuntimeWrappers.cpp
  lib/gc/Transforms/GPU/LinalgToXeGPU.cpp
  test/mlir/test/gc/Transforms/GPU/linalg-to-xegpu-dpas.mlir
  test/mlir/test/gc/gpu-runner/XeGPU/f16_matmul_32x32.mlir
Labels: ready to review

#222 [Build][Bugfix] Fix build failed when GC_ENABLE_DNNL=ON
  cmake/onednn.cmake
Labels: ready to review

#217 [Transform][Fusion] Support fusion for K-tiling deep matmul
  include/gc/Transforms/Passes.td
  lib/gc/Transforms/IterativeTilingAndFusion.cpp
  lib/gc/Transforms/TilingUsingInterfaceX.cpp
  test/mlir/test/gc/Transforms/iterative-tiling-and-fusion.mlir
Labels: ready to review

#90 [Transform][Tiling] Add deep tile support for matmul
  docs/deep_tile_matmul_design.md
  include/gc/Analysis/MatmulConfigAnalysis.h
  include/gc/Transforms/Passes.td
  lib/gc/Analysis/CMakeLists.txt
  lib/gc/Analysis/MatmulConfigAnalysis.cpp
  lib/gc/Transforms/CMakeLists.txt
  lib/gc/Transforms/DeepTileContractionNamedOp.cpp
  lib/gc/Transforms/MergeNestedForall.cpp
  lib/gc/Transforms/Pipeline.cpp
  lib/gc/Transforms/SinkOpIntoInnerLoop.cpp
  lib/gc/Transforms/TileNamed.cpp
  lib/gc/Transforms/TilingUtil.cpp
  lib/gc/Transforms/TilingUtil.hpp
  test/mlir/test/gc/Transforms/deepTileContractionNamedOp.mlir
  test/mlir/test/gc/Transforms/mergeNestedForall.mlir
  test/mlir/test/gc/Transforms/sinkOpIntoInnerLoop.mlir
  test/mlir/unittests/Analysis/CMakeLists.txt
Labels: ready to review

#226 [Transform][Fusion] support fusion for residual pattern
  lib/gc/Transforms/IterativeTilingAndFusion.cpp
  lib/gc/Transforms/TilingUsingInterfaceX.cpp
  test/mlir/test/gc/Transforms/iterative-tiling-and-fusion.mlir
Labels: ready to review

#227 [Transform][Fusion] fix pack/unpack filter
  lib/gc/Transforms/IterativeTilingAndFusion.cpp
  test/mlir/test/gc/Transforms/iterative-tiling-and-fusion.mlir
Labels: ready to review

#187 [Linalgx] Add utils for making and identifying generic packing matmul ops
  include/gc/Dialect/Linalgx/Utils.h
  lib/gc/Dialect/Linalgx/CMakeLists.txt
  lib/gc/Dialect/Linalgx/Utils.cpp
  test/mlir/unittests/CMakeLists.txt
  test/mlir/unittests/Linalgx/CMakeLists.txt
  test/mlir/unittests/Linalgx/TestUtils.cpp
Labels: enhancement, ready to review

#180 Add runtime allocator
  include/gc/Dialect/CPURuntime/IR/CPURuntimeOps.td
  include/gc/Transforms/Passes.h
  include/gc/Transforms/Passes.td
  lib/gc/Dialect/CPURuntime/Transforms/CPURuntimeToLLVM.cpp
  lib/gc/ExecutionEngine/CPURuntime/CMakeLists.txt
  lib/gc/ExecutionEngine/CPURuntime/MemoryPool.cpp
  lib/gc/Transforms/CMakeLists.txt
  lib/gc/Transforms/MemRefToCPURuntime.cpp
  lib/gc/Transforms/Pipeline.cpp
  test/mlir/test/gc/Dialect/CPURuntime/cpu-runner/allocators.mlir
  test/mlir/test/gc/Dialect/CPURuntime/cpuruntime-to-llvm.mlir
  test/mlir/test/gc/Dialect/CPURuntime/memref-to-cpuruntime.mlir
Labels: ready to review

#247 Fix the auto cast of brgemm and the correctness issue of deepTileatmul
  cmake/llvm-version.txt
  lib/gc/Analysis/MatmulConfigAnalysis.cpp
  lib/gc/Transforms/DeepTileContractionNamedOp.cpp
Labels: ready to review

#106 [bench] enable mlir benchmark
  python/CMakeLists.txt
  python/config.py.in
  python/gc_mlir/graph_compiler.py
  test/mlir/test/gc/python/smoketest.py
  tools/README.md
  tools/bench.py
  tools/drivers.py
  tools/example/simple_test.py
  tools/main.py
  tools/utils.py
  tools/workloads/test.mlir
Labels: ready to review

#256 Adding the shared lib GcCpuRuntime for python GraphCompiler
  python/CMakeLists.txt
  python/config.py.in
  python/gc_mlir/graph_compiler.py
Labels: ready to review

#258 Bug fix for correctness check
  lib/gc/ExecutionEngine/CPURuntime/MemoryPool.cpp
  lib/gc/Transforms/MemRefToCPURuntime.cpp
Labels: ready to review

#115 [Runtime][CPU] Introduce DNNL-based BRGEMM runtime
  .github/workflows/clang-tidy.yml
  CMakeLists.txt
  cmake/onednn.cmake
  cmake/onednn_lite_config.cmake
  include/gc/Dialect/OneDNNGraph/CMakeLists.txt
  include/gc/ExecutionEngine/CPURuntime/Microkernel/BrgemmInterface.h
  include/gc/Transforms/CMakeLists.txt
  lib/gc/Dialect/OneDNNGraph/CMakeLists.txt
  lib/gc/ExecutionEngine/CPURuntime/CMakeLists.txt
  lib/gc/ExecutionEngine/CPURuntime/Microkernel/BrgemmNaive.cpp
  lib/gc/ExecutionEngine/CPURuntime/Microkernel/BrgemmOnednn.cpp
  python/CMakeLists.txt
  src/dnnl/CMakeLists.txt
  src/gc-opt/gc-opt.cpp
  test/dnnl/CMakeLists.txt
  test/mlir/test/lit.site.cfg.py.in
  test/mlir/unittests/ExecutionEngine/BrgemmRuntime.cpp
  test/mlir/unittests/ExecutionEngine/CMakeLists.txt
Labels: ready to review

#245 Add CI steps for IMEX build
  .github/workflows/build-gpu-imex.yml
  .github/workflows/build-llvm.yml
  CMakeLists.txt
  cmake/imex-version.txt
  cmake/imex.cmake
  cmake/llvm-version-imex.txt
  scripts/compile.sh
Labels: ci, ready to review, GPU

#265 Correct the llvm version in build script for CPU pipeline
  scripts/compile.sh
Labels: ready to review

#252 [Transform][Vector] Lower operation to tile (virtual) vector
  include/gc/Transforms/Passes.td
  lib/gc/Transforms/CMakeLists.txt
  lib/gc/Transforms/FoldTensorOperation.cpp
  lib/gc/Transforms/LowerToTileVector.cpp
  lib/gc/Transforms/Pipeline.cpp
  test/mlir/test/gc/Transforms/vectorization.mlir
Labels: ready to review

#271 Support generic op in deep tile matmul and enhance matmul config
  include/gc/Analysis/MatmulConfigAnalysis.h
  include/gc/Analysis/TargetDescriptionAnalysis.h
  include/gc/Transforms/Passes.td
  lib/gc/Analysis/MatmulConfigAnalysis.cpp
  lib/gc/Transforms/CMakeLists.txt
  lib/gc/Transforms/DeepTileContractionOp.cpp
  lib/gc/Transforms/Pipeline.cpp
  test/mlir/test/gc/Transforms/deepTileContractionNamedOp.mlir
Labels: ready to review

#275 [UT] Skip BrgemmRuntime UT under unsupported platform
  test/mlir/unittests/ExecutionEngine/BrgemmRuntime.cpp
  test/mlir/unittests/ExecutionEngine/CMakeLists.txt
Labels: bug

#215 Copy DecomposeAggregatedOps pass from tpp-mlir
  include/gc/Transforms/Passes.td
  lib/gc/Transforms/CMakeLists.txt
  lib/gc/Transforms/DecomposeAggregatedOps.cpp
  lib/gc/Transforms/Pipeline.cpp
  test/mlir/test/gc/Transforms/DecomposeAggregatedOps.mlir
Labels: ready to review

#161 Introduce benchgc: a benchmark tool for correctness check
  .github/workflows/build.yml
  .github/workflows/style.yml
  .gitignore
  CMakeLists.txt
  scripts/correctness.sh
  test/CMakeLists.txt
  test/benchgc/.gitignore
  test/benchgc/CMakeLists.txt
  test/benchgc/README.md
  test/benchgc/cases/generic.mlir
  test/benchgc/cases/llama2.mlir
  test/benchgc/cases/reduce.mlir
  test/benchgc/setup.py
  test/benchgc/src/benchgc/CMakeLists.txt
  test/benchgc/src/benchgc/__init__.py
  test/benchgc/src/benchgc/__main__.py
  test/benchgc/src/benchgc/arg/CMakeLists.txt
  test/benchgc/src/benchgc/arg/__init__.py
  test/benchgc/src/benchgc/arg/arg.py
  test/benchgc/src/benchgc/arg/binary.py
  test/benchgc/src/benchgc/arg/compare.py
  test/benchgc/src/benchgc/arg/conv.py
  test/benchgc/src/benchgc/arg/eltwise.py
  test/benchgc/src/benchgc/arg/matmul.py
  test/benchgc/src/benchgc/arg/pool.py
  test/benchgc/src/benchgc/arg/reduce.py
  test/benchgc/src/benchgc/arg/softmax.py
  test/benchgc/src/benchgc/arith/CMakeLists.txt
  test/benchgc/src/benchgc/arith/__init__.py
  test/benchgc/src/benchgc/arith/basic.py
  test/benchgc/src/benchgc/linalg/CMakeLists.txt
  test/benchgc/src/benchgc/linalg/__init__.py
  test/benchgc/src/benchgc/linalg/binary.py
  test/benchgc/src/benchgc/linalg/conv.py
  test/benchgc/src/benchgc/linalg/eltwise.py
  test/benchgc/src/benchgc/linalg/generic.py
  test/benchgc/src/benchgc/linalg/matmul.py
  test/benchgc/src/benchgc/linalg/misc.py
  test/benchgc/src/benchgc/linalg/pool.py
  test/benchgc/src/benchgc/linalg/softmax.py
  test/benchgc/src/benchgc/mlir/CMakeLists.txt
  test/benchgc/src/benchgc/mlir/__init__.py
  test/benchgc/src/benchgc/mlir/arg.py
  test/benchgc/src/benchgc/mlir/module.py
  test/benchgc/src/benchgc/mlir/util.py
  test/benchgc/src/benchgc/runner.py
  test/benchgc/src/benchgc/tensor/CMakeLists.txt
  test/benchgc/src/benchgc/tensor/__init__.py
  test/benchgc/src/benchgc/tensor/basic.py
  test/benchgc/src/benchgc/tensor/shape.py
  test/benchgc/src/benchgc/util.py
Labels: ci, test, ready to review

#179 [Doc] Introduce the validation tool, benchgc
  docs/benchgc_overview.md
Labels: documentation, ready to review

#266 [Transform] Introduce passes for transforming from `linalg` to `microkernel` dialect
  CMakeLists.txt
  include/gc/Dialect/Microkernel/MicrokernelOps.h
  include/gc/Dialect/Microkernel/MicrokernelOps.td
  include/gc/Transforms/CMakeLists.txt
  include/gc/Transforms/Microkernel/BrgemmRuntimeUtils.h
  include/gc/Transforms/Microkernel/CMakeLists.txt
  include/gc/Transforms/Microkernel/MicrokernelPasses.h
  include/gc/Transforms/Microkernel/MicrokernelPasses.td
  include/gc/Transforms/Utils/StructuredOpMatcher.h
  include/gc/Transforms/Utils/ValueUtils.h
  lib/gc/Dialect/Microkernel/CMakeLists.txt
  lib/gc/Dialect/Microkernel/MicrokernelOps.cpp
  lib/gc/ExecutionEngine/CPURuntime/Microkernel/BrgemmNaive.cpp
  lib/gc/Transforms/CMakeLists.txt
  lib/gc/Transforms/Microkernel/CMakeLists.txt
  lib/gc/Transforms/Microkernel/ConvertLinalgToMicrokernel.cpp
  lib/gc/Transforms/Microkernel/ConvertMicrokernelToDnnlFunc.cpp
  lib/gc/Transforms/Microkernel/ExpandMicrokernel.cpp
  lib/gc/Transforms/Utils/ValueUtils.cpp
  src/gc-opt/gc-opt.cpp
  test/mlir/test/gc/Dialect/Microkernel/expand-microkernel.mlir
  test/mlir/test/gc/Dialect/Microkernel/linalg-to-microkernel.mlir
  test/mlir/test/gc/Dialect/Microkernel/microkernel-bufferize.mlir
  test/mlir/test/gc/Dialect/Microkernel/microkernel-to-dnnl-func.mlir
  test/mlir/test/gc/cpu-runner/brgemm-parallel.mlir
Labels: ready to review

#280 [Transform][Fusion] revert consumer fusion for `tensor.pack`
  include/gc/Transforms/Passes.td
  lib/gc/Transforms/IterativeTilingAndFusion.cpp
  test/mlir/test/gc/Transforms/iterative-tiling-and-fusion.mlir
Labels: ready to review

#295 Align the bufferization pipeline according to the upstream doc
  lib/gc/Transforms/Pipeline.cpp
Labels: ready to review

#299 [Binding] update README about LLVM build with python binding
  README.md
Labels: documentation, ready to review

#289 [Transform][Fusion] yield fused producer if necessary
  lib/gc/Transforms/TilingUsingInterfaceX.cpp
  test/mlir/test/gc/Transforms/iterative-tiling-and-fusion.mlir
Labels: ready to review

#302 fix nested parallel loop introduced by linalg op lowering
  lib/gc/Transforms/Pipeline.cpp
Labels: ready to review
