Repository intel/graph-compiler, pull requests merged in 2024-10, with the labels that each got.

#343 Implemented GPU OpenCL runtime
  .github/workflows/clang-tidy.yml
  CMakeLists.txt
  cmake/imex.cmake
  include/gc/ExecutionEngine/GPURuntime/GpuOclRuntime.h
  include/gc/Transforms/Passes.h
  include/gc/Transforms/Passes.td
  include/gc/Utils/Error.h
  include/gc/Utils/Log.h
  lib/gc/ExecutionEngine/CMakeLists.txt
  lib/gc/ExecutionEngine/GPURuntime/CMakeLists.txt
  lib/gc/ExecutionEngine/GPURuntime/ocl/CMakeLists.txt
  lib/gc/ExecutionEngine/GPURuntime/ocl/GpuOclRuntime.cpp
  lib/gc/Transforms/GPU/CMakeLists.txt
  lib/gc/Transforms/GPU/GpuToGpuOcl.cpp
  lib/gc/Transforms/GPU/Pipeline.cpp
  src/gc-opt/CMakeLists.txt
  test/mlir/test/gc/Transforms/GPU/gpu-to-gpuocl.mlir
  test/mlir/test/gc/gpu-runner/XeGPU/f16_matmul_128x64_transpose.mlir
  test/mlir/test/gc/gpu-runner/XeGPU/f16_matmul_128x64_transpose_sep.mlir
  test/mlir/test/gc/gpu-runner/XeGPU/f16_matmul_64x64.mlir
  test/mlir/test/gc/gpu-runner/XeGPU/f16_mlp_32x4096x4096x4096.mlir
  test/mlir/test/gc/gpu-runner/XeGPU/f16_mlp_32x4096x4096x4096_transpose.mlir
  test/mlir/test/gc/gpu-runner/lit.local.cfg
  test/mlir/test/gc/gpu-runner/mlp.mlir
  test/mlir/unittests/ExecutionEngine/CMakeLists.txt
  test/mlir/unittests/ExecutionEngine/GPU/CMakeLists.txt
  test/mlir/unittests/ExecutionEngine/GPU/GpuOclRuntimeTest.cpp
Labels: GPU

#364 Update pinned imex version
  cmake/imex-version.txt
Labels: ready to review

#376 Add config validity check
  include/gc/Analysis/MatmulConfigAnalysis.h
  lib/gc/Analysis/MatmulConfigAnalysis.cpp
Labels: bug
