Repository intel/graph-compiler, pull requests merged in 2024-07, with the labels that each got.

#165 [WIP] Copy LinalgToXeGPU pass from tpp-mlir
  include/gc/Transforms/Passes.h
  include/gc/Transforms/Passes.td
  include/gc/Transforms/Utils/MatcherUtils.h
  include/gc/Transforms/Utils/StructuredOpMatcher.h
  include/gc/Transforms/Utils/ValueUtils.h
  lib/gc/CAPI/CMakeLists.txt
  lib/gc/ExecutionEngine/Driver/CMakeLists.txt
  lib/gc/Transforms/CMakeLists.txt
  lib/gc/Transforms/GPU/CMakeLists.txt
  lib/gc/Transforms/GPU/LinalgToXeGPU.cpp
  lib/gc/Transforms/Utils/CMakeLists.txt
  lib/gc/Transforms/Utils/MatcherUtils.cpp
  lib/gc/Transforms/Utils/StructuredOpMatcher.cpp
  lib/gc/Transforms/Utils/ValueUtils.cpp
  src/gc-opt/CMakeLists.txt
  test/mlir/test/gc/Transforms/GPU/linalg-to-xegpu-dpas.mlir
  test/mlir/test/gc/Transforms/GPU/linalg-to-xegpu-stages.mlir
  test/mlir/test/gc/Transforms/GPU/linalg-to-xegpu.mlir
Labels: WIP

#125 use clang tidy 15
  .github/workflows/clang-tidy.yml
Labels: ci

#114 [Dialect] Introduce `microkernel` dialect
  include/gc/CMakeLists.txt
  include/gc/Dialect/CMakeLists.txt
  include/gc/Dialect/Microkernel/CMakeLists.txt
  include/gc/Dialect/Microkernel/MicrokernelDialect.h
  include/gc/Dialect/Microkernel/MicrokernelDialect.td
  include/gc/Dialect/Microkernel/MicrokernelEnum.h
  include/gc/Dialect/Microkernel/MicrokernelEnum.td
  include/gc/Dialect/Microkernel/MicrokernelOps.h
  include/gc/Dialect/Microkernel/MicrokernelOps.td
  lib/gc/CMakeLists.txt
  lib/gc/Dialect/Microkernel/CMakeLists.txt
  lib/gc/Dialect/Microkernel/MicrokernelDialect.cpp
  lib/gc/Dialect/Microkernel/MicrokernelEnum.cpp
  lib/gc/Dialect/Microkernel/MicrokernelOps.cpp
  src/gc-opt/gc-opt.cpp
Labels: enhancement, ready to review
